### ISSUE TITLE
Highlighting selections on the fly

### ISSUE THREAD

**Issue by sohocoke** [t9md/atom-quick-highlight#1]
Really like the plugin. Would it be feasible to allow making the first highlight work on whatever’s selected? Then the toggle command can make it a persistent highlight, and I can use this plugin to meet the highlighting behaviour in SublimeText 3.

**Comment by t9md** [comment]
So you want automatically highlighted selected word and refresh highlight each time selection change?

I didn't intended that.
How is it useful?

**Comment by sohocoke** [comment]
Sorry for the slow response.

It’s useful to quickly analyse usage of many symbols in a function or method, by clicking around the symbols in the function rapidly. One can quickly understand how pervasive a symbol is being used this way, or to find out you made a typo on one of the references (because it wouldn’t highlight).

Very useful before attempting rename refactors in a Ruby or Coffeescript file, to make up for compilation failures that would catch out bad changes.

Come to think of it, I think it would be awesome the highlight can also show in the minimap. It could help one understand how localised (or not) a symbol is.

**Comment by t9md** [comment]
released as v0.3.5, need Atom v1.1.0 above.
