### ISSUE TITLE
At Atom 1.13.0, highlights are too opaque and cover selections

### ISSUE THREAD

**Issue by jonboiser** [t9md/atom-quick-highlight#16]
Hi, I just noticed this after updating to Atom 1.13.0.

I haven't been able to do much analysis, but here's a screenshot of what's happening:
![screen shot 2017-01-11 at 10 55 13 am](https://cloud.githubusercontent.com/assets/10248067/21855422/81230838-d7ec-11e6-9f3f-31639766aa84.png)

I did some investigation of `div.highlights`, but not sure what style is causing this.

**Comment by t9md** [comment]
what's your setting? I cannot reproduce it.
Btw, I don't recommend decoration style set `highlight`, use `underline` or `box`.

**Comment by jonboiser** [comment]
I  didn't have any custom rules on my stylesheet. I just added the snippet on the README and it fixed it for me. But here's what was going on before I did that: It was giving a background color           of #888888, instead of `transparent`.

<img width="384" alt="screen shot 2017-01-11 at 1 57 38 pm" src="https://cloud.githubusercontent.com/assets/10248067/21862277/8a1e0f90-d806-11e6-886a-7da5f784de15.png">

**Comment by gouegd** [comment]
ah, the code is using the `@syntax-result-marker-color` variable from atom's variables. I suppose your own customisation (or one done by the UI theme you use) set that color and happens to be a bad fit here.

The snippet in the README however uses another variable, `@syntax-text-color`, that's strange, but it worked out better for you.

**Comment by gouegd** [comment]
My mistake, above - the snippet in the README uses transparent for the background color. This is what fixes this issue. I actually just had the same issue upgrading from 0.6.1 to 0.8. I suggest changing the default background color from @syntax-result-marker-color to transparent in the source as well (or any color with transparency)

**Comment by jonboiser** [comment]
@gouegd  Is this the line you're referring to?

https://github.com/t9md/atom-quick-highlight/blob/master/styles/quick-highlight.less#L31

I've been updating this package every release, but hadn't noticed this issue until I upgraded Atom yesterday.

**Comment by gouegd** [comment]
Yes, that's where the opaque background color comes from in our case. You're probably right that it's due to the latest Atom upgrade, I also upgraded that at the same time than most of the packages I use.

**Comment by t9md** [comment]
OK, sorry for this inconvenience, I understand it's frustrated.
Now I could repro and understand what you guys discussing.

## Syntax I tried and result

- Monokai: NG
- Atom Dark: NG
- Atom Light: NG
- Atom Matrial: NG
- One Dark: OK
- One Dark Vivid(Which I use): OK

## Reason

- Currently selection color is directly depending on `@syntax-result-marker-color`.
- And I sed `z-index` to make sure always win another highlight(such as `highlight-search` in `vim-mode-plus`). And it's value is based on when I use completely transparent background-color.

## What was bad.

If this color is defined as some transparency, result is good.
But if not, selection highlight hide selected text(bad).

And setting `z-index` value seems very problematic, will remove.
Will put instruction on README.md.

Will fix soon.

**Comment by t9md** [comment]
released as v0.8.1, thanks for reporting
