### ISSUE TITLE
Change from `underline` to `box`

### ISSUE THREAD

**Issue by arthurcgusmao** [t9md/atom-quick-highlight#27]
Hi. First of all, this package is great!

In the description of the package (README.md) I see that there is possible to enable a box highlight instead of underline. More specifically, from the comments taken from the LESS suggestion on how to override (shown in the snippet below), we see that there may be two classes (`underline-01` and `box-01` for instance):

```less
// quick-highlight use 0 to 7 color
//  for box style, use box-01 to box-07
//  for highlight style, use highlight-01 to highlight-07
```

How do I switch from one to another?
Or should I simply override the border in the class `underline-01`?

Thanks!

**Comment by t9md** [comment]
> How do I switch from one to another?
Via setting, choose type of decoration you want.

<img width="746" alt="decoration" src="https://user-images.githubusercontent.com/155205/38046214-08018744-32fa-11e8-9523-8a8b5a6cb700.png">

**Comment by arthurcgusmao** [comment]
Hey, thanks! I didn't see that this package had a settings tab. Thanks for the great work, this is really helping my workflow.
