### ISSUE TITLE
highlight-selected and quick-highlight

### ISSUE THREAD

**Issue by pvorona** [t9md/atom-quick-highlight#8]
What are the differences between this package and another one called [highlight-selected](https://atom.io/packages/highlight-selected)? As far as i can see they both pretty similar, so please explain motivation to me.

**Comment by Anaghir** [comment]
highlight-selected highlights by double-clicking on a word.
quick-hightlight has multiple selection but no double-clicking.
We need a quick-highlight-selected !

**Comment by t9md** [comment]
quick-highlight can now highlight selection by double click.
